#spring:
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    timeout: 1000
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0

spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Shanghai&useSSL=false